security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        jwt_provider:
            id: App\Auth\Infrastructure\Security\JwtUserProvider

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt)/
            security: false
        api_public:
            pattern: ^/api/(auth/(register|login|refresh)|health)$
            stateless: true
            security: false
        api:
            pattern: ^/api/
            stateless: true
            custom_authenticators:
                - App\Auth\Infrastructure\Security\JwtAuthenticator

    access_control:
        - { path: ^/api/auth/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
